### ISSUE TITLE
Rename DSLs runtime projects

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv-DSLs#2]
Currently the DSLs runtime projects are placed in the `extensions` namspace (`tools.vitruv.extensions.dslsruntime`).
For a unified naming, they should be placed in the `tools.vitruv.dsls` namespace as well. We could either provide a `runtime` subnamespace, i.e., `tools.vitruv.dsls.runtime.*` with * being the langauge name or `tools.vitruv.dsls.*.runtime` with * being the language name. I do not have a strong opinion, does anyone else have?

Concrete action items are:
- [ ] Rename the projects, their metadata and adapt the build
- [ ] Rename the packages within the projects
- [ ] Adapt dependent projects to the changed package names

**Comment by tsaglam** [comment]
I have no strong opinion regarding `*.runtime` vs. `runtime.*` either.
