### ISSUE TITLE
Enum parameter type is not available

### ISSUE THREAD

**Issue by TomWerm** [vitruv-tools/Vitruv-DSLs#67]
A routine calls input [RoutineInput](https://github.com/vitruv-tools/Vitruv-DSLs/blob/d7bd5bc24ce1314510eff115ef81e1da9efa9f86/bundles/tools.vitruv.dsls.reactions/model/TopLevelElements.ecore#L70) uses a [NamedMetaClassReference](https://github.com/vitruv-tools/Vitruv-DSLs/blob/d7bd5bc24ce1314510eff115ef81e1da9efa9f86/bundles/tools.vitruv.dsls.common/model/CommonLanguageElements.ecore#L13) which only allows [EClass](https://github.com/vitruv-tools/Vitruv-DSLs/blob/d7bd5bc24ce1314510eff115ef81e1da9efa9f86/bundles/tools.vitruv.dsls.common/model/CommonLanguageElements.ecore#L11) as parameters. EEnum and EClass both inherit from EClassifier, so an EEnum value cannot be used as parameter. Related to [this issue](https://github.com/vitruv-tools/Vitruv-DSLs/pull/36#discussion_r940268049), so we can update the related reactions once we have changed it to EClassifier. @h4uges @tsaglam

**Comment by h4uges** [comment]
The following reaction is affected: [FamiliesToInsurance](https://github.com/vitruv-tools/Vitruv-DSLs/blob/main/bundles/tools.vitruv.dsls.demo.insurancefamilies/src/tools/vitruv/dsls/demo/insurancefamilies/families2insurance/FamiliesToInsurance.reactions)

- routine updateNameAndCorrespondencesOfCorrespondingInsuranceClient
- routine createInsuranceClient
- routine tryCreateInsuranceClientFromNewMember
- and their usages
