### ISSUE TITLE
Local Variable Name for Candidate Element in Reaction Retrieval

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv-DSLs#9]
Reaction routines allow the definition of a `with` block for each of the `retrieve` statements, as a filter for the candidate to retrieve. This filter is applied to each of the candidates and decides, whether the element shall be retrieved or not. Within the `with` block, the name of the variable to which the retrieved element is assigned is used for referencing the candidate, e.g. `val retrievedElement = retrieve some::class corresponding to someElement with retrievedElement.name = "matchingName"`.
This is already confusing in the single element case, because same variable name as for the finally retrieved element is temporarily used for all candidates. The situation is even worse in the multi element case enabled by `retrieve many`, because in that case the variable name conforms to the returned collection and thus makes no sense for an individual element, e.g. `val retrievedElements = retrieve many some::class corresponding to someElement with retrievedElements.name = "matchingName"`. In this case, the `retrievedElements` within the `with` block actually reference a single candidate.

In consequence, we have to replace the variable name for the candidate within the `with` block with a more suitable name, such as a generic `candidate`. We only have to ensure that there may not be a name clash with another variable that is passed to or visible within the `with` block.

**Comment by JanWittler** [comment]
The implementation of this enhancement is probably a low hanging fruit as soon as the improved syntax is consolidated.

As the Reactions support Xtend code input anyways, we could follow their naming conventions as use `it`?
To avoid name clashes, we could either mark it as a keyword and thus prevent naming elements like it, or provide some renaming functionality to use another name than the default one (like in Xtend `[a|a.name == "abc"]`).

**Comment by HeikoKlare** [comment]
The candidate element is provided as a parameter of a generated method. Thus, it is not a keyword but simply a variable/parameter name. Using `it` as the name is a good idea. It should be possible to use `it` as a parameter name and marking it as an `Extension` should be possible, such that we can use it just like an implicit argument of a lambda expression.
